# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.1.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: jonatasgomesb@gmail.com
author_name: Jônatas Gomes Barbosa da Silva
has_binder: true
has_settings: false
kind: frontend
labextension_name: teaching
project_short_description: A JupyterLab extension.
python_name: teaching
repository: https://github.com/jonatas1n/jupyter-teaching
test: false

